name: Laravel CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Ensure Modules folder exists
      - name: List Modules
        run: |
          ls -l src/Modules
          echo "Modules folder checked"

      # 3️⃣ Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql, intl, bcmath
          tools: composer:v2

      # 4️⃣ Composer install + autoload
      - name: Install Composer Dependencies
        run: |
          cd src
          composer install --no-progress --prefer-dist --optimize-autoloader
          composer dump-autoload

      # 5️⃣ Setup .env
      - name: Setup .env
        run: |
          cp src/.env.example src/.env
          # Replace DB_HOST if needed (GitHub Actions MySQL runs on localhost)
          php -r "file_put_contents('src/.env', str_replace('DB_HOST=127.0.0.1', 'DB_HOST=127.0.0.1', file_get_contents('src/.env')));"

      # 6️⃣ Clear caches (after autoload)
      - name: Clear Laravel caches
        run: |
          cd src
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear

      # 7️⃣ Generate App Key
      - name: Generate App Key
        run: |
          cd src
          php artisan key:generate

      # 8️⃣ Run migrations
      - name: Run Database Migrations
        run: |
          cd src
          php artisan migrate --force

      # 9️⃣ Run Laravel Tests
      - name: Run Tests
        run: |
          cd src
          php artisan test --verbose
