name: Laravel CI

# Trigger workflow on pushes and pull requests to main
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ List Modules folder for debug
      - name: List Modules
        run: |
          ls -l src/Modules
          echo "Modules folder checked"

      # 3️⃣ Setup PHP with required extensions and composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_sqlite, intl, bcmath
          tools: composer:v2

      # 4️⃣ Install Composer dependencies & optimize autoload
      - name: Install Composer Dependencies
        run: |
          cd src
          composer install --no-progress --prefer-dist --optimize-autoloader
          composer dump-autoload -o

      # 5️⃣ Setup .env for SQLite
      - name: Setup .env for SQLite
        run: |
          cd src
          cp .env.example .env
          # Configure SQLite
          php -r "file_put_contents('.env', str_replace('DB_CONNECTION=mysql', 'DB_CONNECTION=sqlite', file_get_contents('.env')));"
          php -r "file_put_contents('.env', str_replace('DB_DATABASE=', 'DB_DATABASE=' . __DIR__ . '/database/database.sqlite', file_get_contents('.env')));"

      # 6️⃣ Ensure SQLite database file exists
      - name: Create SQLite database file
        run: |
          cd src
          mkdir -p database
          touch database/database.sqlite

      # 7️⃣ Clear Laravel caches
      - name: Clear Laravel caches
        run: |
          cd src
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear

      # 8️⃣ Generate Laravel app key
      - name: Generate App Key
        run: |
          cd src
          php artisan key:generate

      # 9️⃣ Run database migrations (on SQLite)
      - name: Run Database Migrations
        run: |
          cd src
          php artisan migrate --force

      # 🔟 Run Laravel tests
      - name: Run Tests
        run: |
          cd src
          php artisan test --verbose
