name: Laravel CI

# কখন রান হবে
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # কোড চেকআউট
      - name: Checkout code
        uses: actions/checkout@v4

      # PHP সেটআপ
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql, intl
          tools: composer:v2

      # Composer dependency install
      - name: Install Dependencies
        run: |
          cd src
          composer install --no-progress --prefer-dist --optimize-autoloader

      # .env ফাইল তৈরি
      - name: Setup .env
        run: |
          cp src/.env.example src/.env
          php -r "file_put_contents('src/.env', str_replace('DB_HOST=127.0.0.1', 'DB_HOST=127.0.0.1', file_get_contents('src/.env')));"

      # App Key generate
      - name: Generate App Key
        run: |
          cd src
          php artisan key:generate

      # DB Migration
      - name: Run Migrations
        run: |
          cd src
          php artisan migrate --force

      # Laravel Tests
      - name: Run Tests
        run: |
          cd src
          php artisan test
