name: Laravel CI

# Trigger workflow on push or pull request to main branch
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # --------------------------
      # 1️⃣ Checkout the repository
      # --------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # --------------------------
      # 2️⃣ Setup PHP
      # --------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_sqlite, intl, bcmath
          tools: composer:v2

      # --------------------------
      # 3️⃣ Install Composer Dependencies
      # --------------------------
      - name: Install Composer Dependencies
        run: |
          cd src
          composer install --no-progress --prefer-dist --optimize-autoloader
          composer dump-autoload

      # --------------------------
      # 4️⃣ Setup .env
      # --------------------------
      - name: Setup .env
        run: |
          cd src
          cp .env.example .env
          mkdir -p database
          touch database/database.sqlite  # create SQLite DB file for CI

      # --------------------------
      # 5️⃣ Clear Laravel caches
      # --------------------------
      - name: Clear Laravel caches
        run: |
          cd src
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear

      # --------------------------
      # 6️⃣ Generate App Key
      # --------------------------
      - name: Generate App Key
        run: |
          cd src
          php artisan key:generate

      # --------------------------
      # 7️⃣ Run migrations (SQLite)
      # --------------------------
      - name: Run Database Migrations
        run: |
          cd src
          php artisan migrate --force

      # --------------------------
      # 8️⃣ Run Tests
      # --------------------------
      - name: Run Laravel Tests
        run: |
          cd src
          php artisan test 
